### ISSUE TITLE
How can I run it on termux

### ISSUE THREAD

**Issue by AbdurRehman1129** [hokireceh/tomarket#1]
![Screenshot_20240910-070514](https://github.com/user-attachments/assets/43ee6ba0-be16-4adc-bfe3-8f6748899d17)
Can you tell me please how can I use it on termux, or if you are using it on another platform please give me video of tutorial.

**Comment by hokireceh** [comment]
you should use ```python bot.py``` not bot.py, who will run it if you don't call it? Try learning how to use Termux and Python first or just join our Telegram

**Comment by hokireceh** [comment]
and that's what bot.py data.txt is 😂 use nano to edit data.txt

**Comment by AbdurRehman1129** [comment]
thanks, I never used this, but I learnt using this

**Comment by AbdurRehman1129** [comment]
thanks, I never used this, but I learnt using this
