### ISSUE TITLE
failed fetch token authorization, check http.log 

### ISSUE THREAD

**Issue by fastnfuriousbd** [hokireceh/tomarket#2]
failed fetch token authorization, check http.log 

Data and token issue with same  data and token i can run tomarket in another python script

**Comment by hokireceh** [comment]
make sure you are using the latest version of python. check python ``` python --version ``` join my telegram and provide an explanation there if the error still occurs


pastikan kamu menggunakan python versi terbaru.

cek python ``` python --version ```

gabung telegram saya dan berikan penjelasannya disana jika masih terjadi eror

**Comment by Mr-Cyb3rgh0st** [comment]
"failed fetch token authorization, check http.log" Fix this problem...

**Comment by hokireceh** [comment]
> "failed fetch token authorization, check http.log" Fix this problem...

Get new query_id or user
